# [https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-a-workflow-when-a-pull-request-is-approved]
on:
  pull_request_review:
    types: [submitted]

#permissions:
#  contents: write

jobs:
  delete_branch:
    uses: sazriel26/github-actions-sandbox/.github/workflows/git-merge-approved-pr.yml@main
    with:
      dry-run: false

