name: Homebrew TAP Self update (Workflow)

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru
    # Sunday
    - cron: '20 7-16/1 * * SUN'
    # Monday-Thursday
    - cron: '5,35 7-16/1 * * MON-THU'
    # Friday
    #- cron: '20 7-16/1 * * FRI'

permissions:
  contents: write
  pull-requests: write

jobs:
  todo:
    uses: sazriel26/github-actions-sandbox/.github/workflows/homebrew-tap-self-update.yml@main
    with:
      dry-run: false

