name: Homebrew TAP Self update (Workflow)

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru
    - cron: '5,35 7-16/1 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  todo:
    uses: sazriel26/github-actions-sandbox/.github/workflows/homebrew-tap-self-update.yml@main
    with:
      dry-run: false

